CORES = {'VERMELHO': '\033[31m', 'AZUL': '\033[34m', 'AMARELO': '\033[33m',
         'VERDE': '\033[32m', 'LILAS': '\033[36m', 'FIM': '\033[m'}

ANIMAIS = ('VACA', 'GATO', 'COBRA', 'GOLFINHO', 'PATO', 'CARANGUEIJO',
           'TUCANO', 'ELEFANTE', 'HIPOPOTAMO', 'LAGARTO', 'POMBO', 'GIRAFA',
           'ABELHA', 'VESPA', 'PAPAGAIO', 'FORMIGA', 'VAGALUME', 'MACACO',
           'CACHORRO', 'ARANHA')

ALIMENTOS = ('FEIJOADA', 'BOLO', 'PAMONHA', 'CUSCUZ', 'ARROZ', 'PIZZA', 'PASTEL',
             'COXINHA', 'SORVETE', 'BISCOITO', 'LARANJA', 'MORANGO', 'CARANBOLA',
             'ACELORA', 'BANANA', 'TOMATE', 'GOIABA', 'CHOCOLATE', 'ERVILHA',
             'BAICON', 'PUDIM')

